# Generated by Django 4.0.5 on 2022-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
